version: 2
updates:
  # Dart
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependabot"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "go_router"
        update-types: ["version-update:semver-major"]
      - dependency-name: "flutter_riverpod"
        update-types: ["version-update:semver-major"]
      - dependency-name: "flutter_form_builder"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependabot"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "kuhnroyal/flutter-fvm-config-action"
        update-types: ["version-update:semver-major"]
      - dependency-name: "subosito/flutter-action"
        update-types: ["version-update:semver-major"]
