name: popcal
version: 1.0.0+8
publish_to: none
environment:
  sdk: ^3.7.2
description: Popup notifications and Calendar scheduling for meeting facilitators and note-takers on a mobile app.
dependencies:
  cloud_firestore: ^5.6.9
  firebase_analytics: ^11.6.0
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.10
  firebase_performance: ^0.10.1+10
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  flutter_hooks: ^0.21.2
  flutter_local_notifications: ^19.4.1
  flutter_riverpod: ^2.6.1
  form_builder_validators: ^11.1.2
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  go_router: ^15.1.2
  go_router_builder: ^3.0.0
  holiday_jp: ^0.0.8
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  package_info_plus: ^8.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  timezone: ^0.10.1
  url_launcher: ^6.3.2
dev_dependencies:
  alchemist: ^0.12.1
  build_runner: ^2.5.3
  custom_lint: ^0.7.6
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed_lint: ^0.0.10
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  pubspec_dependency_sorter: ^1.0.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  test: ^1.25.15
  very_good_analysis: ^9.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
        # フォントサイズは大きいため、利用していない不要なフォントは除外する
        # - asset: assets/fonts/noto_sans_jp/NotoSansJP-Thin.ttf
        #   weight: 100
        # - asset: assets/fonts/noto_sans_jp/NotoSansJP-ExtraLight.ttf
        #   weight: 200
        # - asset: assets/fonts/noto_sans_jp/NotoSansJP-Light.ttf
        #   weight: 300
        # FontWeight.normal (デフォルト)
        - asset: assets/fonts/noto_sans_jp/NotoSansJP-Regular.ttf
          weight: 400
        # - asset: assets/fonts/noto_sans_jp/NotoSansJP-Medium.ttf
        #   weight: 500
        # w600は利用
        - asset: assets/fonts/noto_sans_jp/NotoSansJP-SemiBold.ttf
          weight: 600
        # FontWeight.bold
        - asset: assets/fonts/noto_sans_jp/NotoSansJP-Bold.ttf
          weight: 700
        # - asset: assets/fonts/noto_sans_jp/NotoSansJP-ExtraBold.ttf
        #   weight: 800
        # - asset: assets/fonts/noto_sans_jp/NotoSansJP-Black.ttf
        #   weight: 900
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_12:
    icon_background_color: "#ffffff"
    image: assets/images/splash.png
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png
