// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdFyrlJ77NWUBM5RgcPijr7DkhT1EQPU4',
    appId: '1:839692849399:web:31d92ba204bb6ab10243f2',
    messagingSenderId: '839692849399',
    projectId: 'popcal-e709a',
    authDomain: 'popcal-e709a.firebaseapp.com',
    storageBucket: 'popcal-e709a.firebasestorage.app',
    measurementId: 'G-DSDZ510H18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrp5KYKRFO2rm1Bp-7-SywY6hRrZIg46o',
    appId: '1:839692849399:android:dced36efb1368f1e0243f2',
    messagingSenderId: '839692849399',
    projectId: 'popcal-e709a',
    storageBucket: 'popcal-e709a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtNup3UqHFxK2-QZclLHkqhIlz-ted1uM',
    appId: '1:839692849399:ios:727c3f4ec9552de40243f2',
    messagingSenderId: '839692849399',
    projectId: 'popcal-e709a',
    storageBucket: 'popcal-e709a.firebasestorage.app',
    iosBundleId: 'com.example.popcal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtNup3UqHFxK2-QZclLHkqhIlz-ted1uM',
    appId: '1:839692849399:ios:727c3f4ec9552de40243f2',
    messagingSenderId: '839692849399',
    projectId: 'popcal-e709a',
    storageBucket: 'popcal-e709a.firebasestorage.app',
    iosBundleId: 'com.example.popcal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdFyrlJ77NWUBM5RgcPijr7DkhT1EQPU4',
    appId: '1:839692849399:web:1ef42cdd47b4c3ff0243f2',
    messagingSenderId: '839692849399',
    projectId: 'popcal-e709a',
    authDomain: 'popcal-e709a.firebaseapp.com',
    storageBucket: 'popcal-e709a.firebasestorage.app',
    measurementId: 'G-V9XBTNTWFN',
  );

}