have_fun: false
ignore_patterns:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
code_review:
  disable: false
  comment_severity_threshold: "MEDIUM"
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
